# Distroless Dockerfile

# Stage 1: Build stage
FROM node:16 AS build

WORKDIR /app

COPY package.json ./
RUN npm install

COPY . .

# Stage 2: Production stage (Distroless)
FROM gcr.io/distroless/nodejs

WORKDIR /app

COPY --from=build /app .

EXPOSE 3000

CMD ["server.js"]
